"""Every door of the gateway, in the order the app includes them."""

from __future__ import annotations

from fastapi import APIRouter

from pinecall.api import (
    agent_memory,
    box_brand,
    box_mail,
    box_signin,
    contacts,
    dialling,
    discovery,
    extraction,
    fleet,
    floor,
    forgot,
    hold_audio,
    insights,
    judging,
    keys,
    knowledge,
    lexicon,
    listen,
    login,
    login_google,
    login_orgs,
    login_sso,
    managed,
    members,
    numbers,
    ops_members,
    org_mail,
    orgs,
    outbound,
    pairing,
    persona_runs,
    personas,
    pipeline,
    processes,
    provider_keys,
    providers,
    routes,
    signup,
    sso,
    supervise_seat,
    threads,
    tokens,
    tuning,
    usage,
    whoami,
    widget,
)
from pinecall.api.agents import dev, socket
from pinecall.api.agents import endpoints as agents
from pinecall.api.agents import provider_keys as agents_provider_keys
from pinecall.api.calls import chat, commands, events, listing, lookup, recording, state, tools
from pinecall.api.evals import caller, judge, replay, runs, voice
from pinecall.api.supervise import verbs
from pinecall.api.whatsapp import webhook

# One door per line, in the order a reader meets them: the app's socket and the calls it answers,
# the desk and the suites, the tenant's own tables, the operator's under /v1/ops, and last the
# org's people — who they are, how they sign in, and whose key just knocked.
DOORS: tuple[APIRouter, ...] = (
    socket.router,
    agents.router,
    agents_provider_keys.router,
    dev.router,
    personas.router,
    persona_runs.router,
    events.router,
    state.router,
    listing.router,
    recording.router,
    chat.router,
    tools.router,
    commands.router,
    lookup.router,
    verbs.router,
    replay.router,
    judge.router,
    runs.router,
    caller.router,
    voice.router,
    routes.router,
    routes.operator,
    keys.router,
    processes.router,
    provider_keys.router,
    providers.router,
    orgs.operator,
    provider_keys.operator,
    usage.operator,
    usage.router,
    fleet.router,
    fleet.operator,
    pipeline.router,
    hold_audio.router,
    tuning.router,
    lexicon.router,
    widget.router,
    tokens.router,
    listen.router,
    supervise_seat.router,
    webhook.router,
    knowledge.router,
    contacts.router,
    agent_memory.router,
    extraction.router,
    members.router,
    ops_members.operator,
    login.router,
    login_orgs.router,
    forgot.router,
    login_sso.router,
    login_google.router,
    sso.router,
    sso.operator,
    org_mail.router,
    box_mail.operator,
    box_brand.operator,
    box_signin.operator,
    pairing.router,
    floor.router,
    threads.router,
    insights.router,
    judging.router,
    numbers.router,
    managed.router,
    outbound.router,
    dialling.router,
    signup.router,
    whoami.router,
    whoami.operator,
    discovery.router,
)
