# smart-turn-livekit ships no types. What is here is the shape livekit's _StreamingTurnDetector
# protocol reads off SmartTurnDetector, so a session may take it as its turn_detection.

import asyncio
from collections.abc import Callable

from livekit import rtc
from livekit.agents import APIConnectOptions
from livekit.agents.language import LanguageCode
from livekit.agents.voice.turn import TurnDetectionEvent

class Prediction:
    probability: float
    threshold: float
    complete: bool
    inference_s: float
    audio_s: float
    at: float

class SmartTurnDetectorStream:
    @property
    def model(self) -> str: ...
    @property
    def provider(self) -> str: ...
    @property
    def is_fallback(self) -> bool: ...
    @property
    def prediction_timeout(self) -> float: ...
    async def unlikely_threshold(self, language: LanguageCode | None = ...) -> float | None: ...
    async def backchannel_threshold(self, language: LanguageCode | None = ...) -> float | None: ...
    async def supports_language(self, language: LanguageCode | None = ...) -> bool: ...
    def predict(self) -> asyncio.Future[TurnDetectionEvent]: ...
    def cancel_inference(self, *, timed_out: bool = ...) -> None: ...
    def flush(self, reason: str | None = ...) -> None: ...
    def push_audio(self, frame: rtc.AudioFrame) -> None: ...
    def end_input(self) -> None: ...
    async def aclose(self) -> None: ...

class SmartTurnDetector:
    threshold: float
    prediction_timeout: float
    def __init__(
        self,
        model: str = ...,
        *,
        model_path: str | None = ...,
        threshold: float | dict[str, float] | None = ...,
        operating_point: str = ...,
        languages: tuple[str, ...] | None = ...,
        allow_unknown_language: bool = ...,
        prediction_timeout: float = ...,
        on_prediction: Callable[[Prediction], None] | None = ...,
        warmup: bool = ...,
        cpu_count: int = ...,
        local_only: bool = ...,
    ) -> None: ...
    @property
    def model(self) -> str: ...
    @property
    def provider(self) -> str: ...
    def supports_language(self, language: str | None = ...) -> bool: ...
    def stream(self, *, conn_options: APIConnectOptions = ...) -> SmartTurnDetectorStream: ...
    async def aclose(self) -> None: ...
