"""The gateway fixtures this suite drives: named here, because a conftest reaches no sibling."""

from tests.api.conftest import (
    admission,
    embedder,
    fleet,
    graph,
    keys,
    keys_asked,
    knowledge,
    live,
    llm,
    llms,
    logs,
    lookups,
    memory,
    models_asked,
    ops_http,
    orgs,
    registry,
    routes,
    settings,
    snapshots,
    store,
    threads,
    tokens,
    tuning,
    vault,
    wired,
)

# pytest collects a fixture it finds in a conftest's namespace; this list is what says so out loud.
__all__ = [
    "admission",
    "embedder",
    "fleet",
    "graph",
    "keys",
    "keys_asked",
    "knowledge",
    "live",
    "llm",
    "llms",
    "logs",
    "lookups",
    "memory",
    "models_asked",
    "ops_http",
    "orgs",
    "registry",
    "routes",
    "settings",
    "snapshots",
    "store",
    "threads",
    "tokens",
    "tuning",
    "vault",
    "wired",
]
